# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
vars:
  PROJECT: "vex"
  PACKAGE: "github.com/lrstanley/vex"
env:
  GOEXPERIMENT: jsonv2,greenteagc
dotenv: [".env"]
method: timestamp
tasks:
  default:
    desc: build the project
    cmds:
      - task: build
  vault:up:
    desc: start mock cluster
    dir: mock-cluster
    cmds:
      - go run . start
  vault:down:
    desc: stop mock cluster
    dir: mock-cluster
    cmds:
      - go run . stop
  vault:rm:
    desc: remove mock cluster and data
    dir: mock-cluster
    cmds:
      - go run . rm
  vault:env:
    desc: update .env file with mock cluster credentials -- use "task vault:env -- <user-id>" to change users
    dir: mock-cluster
    cmds:
      - go run . env --id {{ or .CLI_ARGS "token" }} > ../.env
  license:
    desc: generate license headers
    cmds:
      - curl -sL https://liam.sh/-/gh/g/license-header.sh | bash -s
  clean:
    desc: clean build artifacts
    cmds:
      - rm -rfv {{.PROJECT}}
  fetch:
    desc: tidy go modules
    aliases: [tidy, download]
    cmds:
      - go mod tidy
  up:
    desc: update dependencies
    aliases: [update, upgrade]
    cmds:
      - go get -u ./...
      - go get -u -t ./...
      - task: fetch
  prepare:
    desc: prepare build environment
    deps: [fetch]
    aliases: [init, generate, gen]
    sources:
      - internal/ui/styles/theme.go
    generates:
      - internal/ui/styles/theme.gen.go
    cmds:
      - go generate -x ./...
  profile:cpu: go tool pprof -http :6061 'http://127.0.0.1:6060/debug/pprof/profile?seconds=15'
  profile:heap: go tool pprof -http :6061 'http://127.0.0.1:6060/debug/pprof/heap'
  profile:allocs: go tool pprof -http :6061 'http://127.0.0.1:6060/debug/pprof/allocs'
  dlv:
    desc: run with delve debugger
    deps: [prepare]
    aliases: [delve, debugger]
    cmds:
      - |
        dlv debug \
          --headless \
          --listen=:2345 \
          --api-version=2 \
          --log \
          --allow-non-terminal-interactive \
          {{.PACKAGE}} -- --logging.level=debug {{.CLI_ARGS}}
  debug:
    desc: run in debug mode
    deps: [prepare]
    aliases: [dev, run]
    interactive: true
    env:
      HTTP_TRACE: true
    cmds:
      - |
        go run {{.PACKAGE}} \
          --logging.level=debug \
          --enable-pprof \
          {{.CLI_ARGS}}
  debug:basic:
    desc: run in debug mode
    deps: [prepare]
    interactive: true
    cmds:
      - |
        TERM="xterm-color" COLORTERM="xterm-color" go run {{.PACKAGE}} \
          --logging.level=debug \
          --enable-pprof \
          {{.CLI_ARGS}}
  debug:unset:
    desc: unset env vars
    cmds:
      - |
        VAULT_ADDR=http://localhost:8200 VAULT_TOKEN=some-invalid-token go run {{.PACKAGE}} \
          --logging.level=debug \
          --enable-pprof \
          {{.CLI_ARGS}}
  build:
    desc: build the application
    deps: [prepare]
    env:
      CGO_ENABLED: 0
    cmds:
      - |
        go build \
          -ldflags '-d -s -w -extldflags=-static' \
          -tags=netgo,osusergo,static_build \
          -installsuffix netgo \
          -trimpath \
          -o {{.PROJECT}} {{.PACKAGE}}
  test:
    desc: run tests
    deps: [prepare]
    cmds:
      - go test -count 5 -p 3 {{ or .CLI_ARGS "./..." }}
  test:update:
    desc: run tests and update snapshots
    deps: [prepare]
    cmds:
      - UPDATE_SNAPS=always go test -count 2 -p 3 {{ or .CLI_ARGS "./..." }}
  lint:
    desc: run linter
    deps: [prepare]
    cmds:
      - golangci-lint run
  fmt:
    desc: format code
    deps: [prepare]
    aliases: [format]
    cmds:
      - gofumpt -w .
  tape:
    desc: record demo GIFs
    deps: [build]
    aliases: [demo]
    cmds:
      - mkdir -p tmp/
      - go run github.com/charmbracelet/vhs@latest demo.tape
      - gifsicle -O3 --colors 256 --lossy=30 -o tmp/demo-optimized-$(date +%Y-%m-%d-%H-%M-%S).gif tmp/demo.gif
      - task: clean
